name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - master  # 触发部署的分支 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Alibaba Cloud Docker Registry
      uses: docker/login-action@v1
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.ALIBABA_CLOUD_USERNAME }}
        password: ${{ secrets.ALIBABA_CLOUD_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: registry.cn-beijing.aliyuncs.com/richinfoai/ai-robot-client:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Alibaba Cloud server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker pull registry.cn-beijing.aliyuncs.com/richinfoai/ai-robot-client:latest
          docker stop ai-robot-client || true
          docker rm ai-robot-client || true
          docker run -d --name ai-robot-client -p 40000:80 registry.cn-beijing.aliyuncs.com/richinfoai/ai-robot-client:latest

